version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-stretch
    steps:
      - checkout
      - run: sudo pip install pipenv
      - run: pipenv lock
      - run: pipenv install --ignore-pipfile --dev
      - run: pipenv shell
      - run: pytest
