version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-stretch
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest
  build:
    docker:
      - image: circleci/python:3.7.4-stretch
      steps:
        - checkout
        - run: pipenv shell
        - run: pipenv lock
        - run: pipenv install --ignore-pipfile
        - run: pytest